apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gfghaaui8-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gfghaaui8-java-quarkus-gitops